---
- name: "Extract Zipped Artifact"
  become: true
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /var/lib/backend

- name: "Install node.js backend package"
  become: true
  command: npm install
  args:
    chdir: /var/lib/backend

- name: "Start the backend with pm2"
  become: true
  command: pm2 start npm -- start
  args:
    chdir: /var/lib/backend

