---
- name: "Extract Zipped Artifact"
  become: true
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /var/lib/backend

- name: "Install node.js backend package"
  become: true
  community.general.npm:
    name: backend
    path: /var/lib/backend

- name: "Start the backend with pm2"
  become: true
  shell: |
    cd /var/lib/backend
    pm2 stop default
    pm2 start npm -- start

